/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoadsafeOperationsRouteImport } from './routes/roadsafe-operations'
import { Route as RoadsafeNotificationsRouteImport } from './routes/roadsafe-notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as MiniSiteSlugRouteImport } from './routes/$miniSiteSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionsIndexRouteImport } from './routes/regions.index'
import { Route as BarangaysIndexRouteImport } from './routes/barangays.index'
import { Route as RegionsRegionRouteImport } from './routes/regions.$region'
import { Route as ProvincesProvinceRouteImport } from './routes/provinces.$province'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as InventoryBusinessIdRouteImport } from './routes/inventory.$businessId'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as ApiRoadsafeRouteRouteImport } from './routes/api/roadsafe/route'
import { Route as DashboardBusinessIdRouteImport } from './routes/dashboard.business.$id'
import { Route as BarangaysCityBarangayRouteImport } from './routes/barangays.$city.$barangay'
import { Route as DashboardBusinessIdInventoryRouteImport } from './routes/dashboard.business.$id.inventory'
import { Route as ApiPublicHooksRoadsafeIngestRouteImport } from './routes/api/public/hooks/roadsafe-ingest'
import { Route as ApiPublicHooksRoadsafeDeliverRouteImport } from './routes/api/public/hooks/roadsafe-deliver'
import { Route as ApiPublicHooksFuelSyncRouteImport } from './routes/api/public/hooks/fuel-sync'
import { Route as ApiPublicHooksFuelStationsSyncRouteImport } from './routes/api/public/hooks/fuel-stations-sync'
import { Route as ApiPublicHooksBusinessOsmSyncRouteImport } from './routes/api/public/hooks/business-osm-sync'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsafeOperationsRoute = RoadsafeOperationsRouteImport.update({
  id: '/roadsafe-operations',
  path: '/roadsafe-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsafeNotificationsRoute = RoadsafeNotificationsRouteImport.update({
  id: '/roadsafe-notifications',
  path: '/roadsafe-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniSiteSlugRoute = MiniSiteSlugRouteImport.update({
  id: '/$miniSiteSlug',
  path: '/$miniSiteSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarangaysIndexRoute = BarangaysIndexRouteImport.update({
  id: '/barangays/',
  path: '/barangays/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRegionRoute = RegionsRegionRouteImport.update({
  id: '/regions/$region',
  path: '/regions/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesProvinceRoute = ProvincesProvinceRouteImport.update({
  id: '/provinces/$province',
  path: '/provinces/$province',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const InventoryBusinessIdRoute = InventoryBusinessIdRouteImport.update({
  id: '/inventory/$businessId',
  path: '/inventory/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadsafeRouteRoute = ApiRoadsafeRouteRouteImport.update({
  id: '/api/roadsafe',
  path: '/api/roadsafe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdRoute = DashboardBusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const BarangaysCityBarangayRoute = BarangaysCityBarangayRouteImport.update({
  id: '/barangays/$city/$barangay',
  path: '/barangays/$city/$barangay',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdInventoryRoute =
  DashboardBusinessIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => DashboardBusinessIdRoute,
  } as any)
const ApiPublicHooksRoadsafeIngestRoute =
  ApiPublicHooksRoadsafeIngestRouteImport.update({
    id: '/api/public/hooks/roadsafe-ingest',
    path: '/api/public/hooks/roadsafe-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRoadsafeDeliverRoute =
  ApiPublicHooksRoadsafeDeliverRouteImport.update({
    id: '/api/public/hooks/roadsafe-deliver',
    path: '/api/public/hooks/roadsafe-deliver',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFuelSyncRoute = ApiPublicHooksFuelSyncRouteImport.update({
  id: '/api/public/hooks/fuel-sync',
  path: '/api/public/hooks/fuel-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFuelStationsSyncRoute =
  ApiPublicHooksFuelStationsSyncRouteImport.update({
    id: '/api/public/hooks/fuel-stations-sync',
    path: '/api/public/hooks/fuel-stations-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBusinessOsmSyncRoute =
  ApiPublicHooksBusinessOsmSyncRouteImport.update({
    id: '/api/public/hooks/business-osm-sync',
    path: '/api/public/hooks/business-osm-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$miniSiteSlug': typeof MiniSiteSlugRoute
  '/add-business': typeof AddBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/roadsafe-notifications': typeof RoadsafeNotificationsRoute
  '/roadsafe-operations': typeof RoadsafeOperationsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/roadsafe': typeof ApiRoadsafeRouteRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/cities/$city': typeof CitiesCityRoute
  '/inventory/$businessId': typeof InventoryBusinessIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/barangays/': typeof BarangaysIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRouteWithChildren
  '/api/public/hooks/business-osm-sync': typeof ApiPublicHooksBusinessOsmSyncRoute
  '/api/public/hooks/fuel-stations-sync': typeof ApiPublicHooksFuelStationsSyncRoute
  '/api/public/hooks/fuel-sync': typeof ApiPublicHooksFuelSyncRoute
  '/api/public/hooks/roadsafe-deliver': typeof ApiPublicHooksRoadsafeDeliverRoute
  '/api/public/hooks/roadsafe-ingest': typeof ApiPublicHooksRoadsafeIngestRoute
  '/dashboard/business/$id/inventory': typeof DashboardBusinessIdInventoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$miniSiteSlug': typeof MiniSiteSlugRoute
  '/add-business': typeof AddBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/roadsafe-notifications': typeof RoadsafeNotificationsRoute
  '/roadsafe-operations': typeof RoadsafeOperationsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/roadsafe': typeof ApiRoadsafeRouteRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/cities/$city': typeof CitiesCityRoute
  '/inventory/$businessId': typeof InventoryBusinessIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/barangays': typeof BarangaysIndexRoute
  '/regions': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRouteWithChildren
  '/api/public/hooks/business-osm-sync': typeof ApiPublicHooksBusinessOsmSyncRoute
  '/api/public/hooks/fuel-stations-sync': typeof ApiPublicHooksFuelStationsSyncRoute
  '/api/public/hooks/fuel-sync': typeof ApiPublicHooksFuelSyncRoute
  '/api/public/hooks/roadsafe-deliver': typeof ApiPublicHooksRoadsafeDeliverRoute
  '/api/public/hooks/roadsafe-ingest': typeof ApiPublicHooksRoadsafeIngestRoute
  '/dashboard/business/$id/inventory': typeof DashboardBusinessIdInventoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$miniSiteSlug': typeof MiniSiteSlugRoute
  '/add-business': typeof AddBusinessRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/roadsafe-notifications': typeof RoadsafeNotificationsRoute
  '/roadsafe-operations': typeof RoadsafeOperationsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/api/roadsafe': typeof ApiRoadsafeRouteRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/cities/$city': typeof CitiesCityRoute
  '/inventory/$businessId': typeof InventoryBusinessIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/barangays/': typeof BarangaysIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRouteWithChildren
  '/api/public/hooks/business-osm-sync': typeof ApiPublicHooksBusinessOsmSyncRoute
  '/api/public/hooks/fuel-stations-sync': typeof ApiPublicHooksFuelStationsSyncRoute
  '/api/public/hooks/fuel-sync': typeof ApiPublicHooksFuelSyncRoute
  '/api/public/hooks/roadsafe-deliver': typeof ApiPublicHooksRoadsafeDeliverRoute
  '/api/public/hooks/roadsafe-ingest': typeof ApiPublicHooksRoadsafeIngestRoute
  '/dashboard/business/$id/inventory': typeof DashboardBusinessIdInventoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$miniSiteSlug'
    | '/add-business'
    | '/dashboard'
    | '/fuel'
    | '/import'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/roadsafe-notifications'
    | '/roadsafe-operations'
    | '/search'
    | '/signup'
    | '/api/roadsafe'
    | '/business/$slug'
    | '/categories/$category'
    | '/cities/$city'
    | '/inventory/$businessId'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/barangays/'
    | '/regions/'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
    | '/api/public/hooks/business-osm-sync'
    | '/api/public/hooks/fuel-stations-sync'
    | '/api/public/hooks/fuel-sync'
    | '/api/public/hooks/roadsafe-deliver'
    | '/api/public/hooks/roadsafe-ingest'
    | '/dashboard/business/$id/inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$miniSiteSlug'
    | '/add-business'
    | '/dashboard'
    | '/fuel'
    | '/import'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/roadsafe-notifications'
    | '/roadsafe-operations'
    | '/search'
    | '/signup'
    | '/api/roadsafe'
    | '/business/$slug'
    | '/categories/$category'
    | '/cities/$city'
    | '/inventory/$businessId'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/barangays'
    | '/regions'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
    | '/api/public/hooks/business-osm-sync'
    | '/api/public/hooks/fuel-stations-sync'
    | '/api/public/hooks/fuel-sync'
    | '/api/public/hooks/roadsafe-deliver'
    | '/api/public/hooks/roadsafe-ingest'
    | '/dashboard/business/$id/inventory'
  id:
    | '__root__'
    | '/'
    | '/$miniSiteSlug'
    | '/add-business'
    | '/dashboard'
    | '/fuel'
    | '/import'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/roadsafe-notifications'
    | '/roadsafe-operations'
    | '/search'
    | '/signup'
    | '/api/roadsafe'
    | '/business/$slug'
    | '/categories/$category'
    | '/cities/$city'
    | '/inventory/$businessId'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/barangays/'
    | '/regions/'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
    | '/api/public/hooks/business-osm-sync'
    | '/api/public/hooks/fuel-stations-sync'
    | '/api/public/hooks/fuel-sync'
    | '/api/public/hooks/roadsafe-deliver'
    | '/api/public/hooks/roadsafe-ingest'
    | '/dashboard/business/$id/inventory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiniSiteSlugRoute: typeof MiniSiteSlugRoute
  AddBusinessRoute: typeof AddBusinessRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FuelRoute: typeof FuelRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadsafeNotificationsRoute: typeof RoadsafeNotificationsRoute
  RoadsafeOperationsRoute: typeof RoadsafeOperationsRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  ApiRoadsafeRouteRoute: typeof ApiRoadsafeRouteRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  CitiesCityRoute: typeof CitiesCityRoute
  InventoryBusinessIdRoute: typeof InventoryBusinessIdRoute
  ProvincesProvinceRoute: typeof ProvincesProvinceRoute
  RegionsRegionRoute: typeof RegionsRegionRoute
  BarangaysIndexRoute: typeof BarangaysIndexRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
  BarangaysCityBarangayRoute: typeof BarangaysCityBarangayRoute
  ApiPublicHooksBusinessOsmSyncRoute: typeof ApiPublicHooksBusinessOsmSyncRoute
  ApiPublicHooksFuelStationsSyncRoute: typeof ApiPublicHooksFuelStationsSyncRoute
  ApiPublicHooksFuelSyncRoute: typeof ApiPublicHooksFuelSyncRoute
  ApiPublicHooksRoadsafeDeliverRoute: typeof ApiPublicHooksRoadsafeDeliverRoute
  ApiPublicHooksRoadsafeIngestRoute: typeof ApiPublicHooksRoadsafeIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadsafe-operations': {
      id: '/roadsafe-operations'
      path: '/roadsafe-operations'
      fullPath: '/roadsafe-operations'
      preLoaderRoute: typeof RoadsafeOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadsafe-notifications': {
      id: '/roadsafe-notifications'
      path: '/roadsafe-notifications'
      fullPath: '/roadsafe-notifications'
      preLoaderRoute: typeof RoadsafeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$miniSiteSlug': {
      id: '/$miniSiteSlug'
      path: '/$miniSiteSlug'
      fullPath: '/$miniSiteSlug'
      preLoaderRoute: typeof MiniSiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barangays/': {
      id: '/barangays/'
      path: '/barangays'
      fullPath: '/barangays/'
      preLoaderRoute: typeof BarangaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$region': {
      id: '/regions/$region'
      path: '/regions/$region'
      fullPath: '/regions/$region'
      preLoaderRoute: typeof RegionsRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/$province': {
      id: '/provinces/$province'
      path: '/provinces/$province'
      fullPath: '/provinces/$province'
      preLoaderRoute: typeof ProvincesProvinceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/inventory/$businessId': {
      id: '/inventory/$businessId'
      path: '/inventory/$businessId'
      fullPath: '/inventory/$businessId'
      preLoaderRoute: typeof InventoryBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roadsafe': {
      id: '/api/roadsafe'
      path: '/api/roadsafe'
      fullPath: '/api/roadsafe'
      preLoaderRoute: typeof ApiRoadsafeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/$id': {
      id: '/dashboard/business/$id'
      path: '/business/$id'
      fullPath: '/dashboard/business/$id'
      preLoaderRoute: typeof DashboardBusinessIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/barangays/$city/$barangay': {
      id: '/barangays/$city/$barangay'
      path: '/barangays/$city/$barangay'
      fullPath: '/barangays/$city/$barangay'
      preLoaderRoute: typeof BarangaysCityBarangayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/$id/inventory': {
      id: '/dashboard/business/$id/inventory'
      path: '/inventory'
      fullPath: '/dashboard/business/$id/inventory'
      preLoaderRoute: typeof DashboardBusinessIdInventoryRouteImport
      parentRoute: typeof DashboardBusinessIdRoute
    }
    '/api/public/hooks/roadsafe-ingest': {
      id: '/api/public/hooks/roadsafe-ingest'
      path: '/api/public/hooks/roadsafe-ingest'
      fullPath: '/api/public/hooks/roadsafe-ingest'
      preLoaderRoute: typeof ApiPublicHooksRoadsafeIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/roadsafe-deliver': {
      id: '/api/public/hooks/roadsafe-deliver'
      path: '/api/public/hooks/roadsafe-deliver'
      fullPath: '/api/public/hooks/roadsafe-deliver'
      preLoaderRoute: typeof ApiPublicHooksRoadsafeDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fuel-sync': {
      id: '/api/public/hooks/fuel-sync'
      path: '/api/public/hooks/fuel-sync'
      fullPath: '/api/public/hooks/fuel-sync'
      preLoaderRoute: typeof ApiPublicHooksFuelSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fuel-stations-sync': {
      id: '/api/public/hooks/fuel-stations-sync'
      path: '/api/public/hooks/fuel-stations-sync'
      fullPath: '/api/public/hooks/fuel-stations-sync'
      preLoaderRoute: typeof ApiPublicHooksFuelStationsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/business-osm-sync': {
      id: '/api/public/hooks/business-osm-sync'
      path: '/api/public/hooks/business-osm-sync'
      fullPath: '/api/public/hooks/business-osm-sync'
      preLoaderRoute: typeof ApiPublicHooksBusinessOsmSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardBusinessIdRouteChildren {
  DashboardBusinessIdInventoryRoute: typeof DashboardBusinessIdInventoryRoute
}

const DashboardBusinessIdRouteChildren: DashboardBusinessIdRouteChildren = {
  DashboardBusinessIdInventoryRoute: DashboardBusinessIdInventoryRoute,
}

const DashboardBusinessIdRouteWithChildren =
  DashboardBusinessIdRoute._addFileChildren(DashboardBusinessIdRouteChildren)

interface DashboardRouteChildren {
  DashboardBusinessIdRoute: typeof DashboardBusinessIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessIdRoute: DashboardBusinessIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiniSiteSlugRoute: MiniSiteSlugRoute,
  AddBusinessRoute: AddBusinessRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FuelRoute: FuelRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadsafeNotificationsRoute: RoadsafeNotificationsRoute,
  RoadsafeOperationsRoute: RoadsafeOperationsRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  ApiRoadsafeRouteRoute: ApiRoadsafeRouteRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  CitiesCityRoute: CitiesCityRoute,
  InventoryBusinessIdRoute: InventoryBusinessIdRoute,
  ProvincesProvinceRoute: ProvincesProvinceRoute,
  RegionsRegionRoute: RegionsRegionRoute,
  BarangaysIndexRoute: BarangaysIndexRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  BarangaysCityBarangayRoute: BarangaysCityBarangayRoute,
  ApiPublicHooksBusinessOsmSyncRoute: ApiPublicHooksBusinessOsmSyncRoute,
  ApiPublicHooksFuelStationsSyncRoute: ApiPublicHooksFuelStationsSyncRoute,
  ApiPublicHooksFuelSyncRoute: ApiPublicHooksFuelSyncRoute,
  ApiPublicHooksRoadsafeDeliverRoute: ApiPublicHooksRoadsafeDeliverRoute,
  ApiPublicHooksRoadsafeIngestRoute: ApiPublicHooksRoadsafeIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
