/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionsIndexRouteImport } from './routes/regions.index'
import { Route as RegionsRegionRouteImport } from './routes/regions.$region'
import { Route as ProvincesProvinceRouteImport } from './routes/provinces.$province'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as DashboardBusinessIdRouteImport } from './routes/dashboard.business.$id'
import { Route as BarangaysCityBarangayRouteImport } from './routes/barangays.$city.$barangay'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRegionRoute = RegionsRegionRouteImport.update({
  id: '/regions/$region',
  path: '/regions/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesProvinceRoute = ProvincesProvinceRouteImport.update({
  id: '/provinces/$province',
  path: '/provinces/$province',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdRoute = DashboardBusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const BarangaysCityBarangayRoute = BarangaysCityBarangayRouteImport.update({
  id: '/barangays/$city/$barangay',
  path: '/barangays/$city/$barangay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/regions/': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/regions': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/provinces/$province': typeof ProvincesProvinceRoute
  '/regions/$region': typeof RegionsRegionRoute
  '/regions/': typeof RegionsIndexRoute
  '/barangays/$city/$barangay': typeof BarangaysCityBarangayRoute
  '/dashboard/business/$id': typeof DashboardBusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fuel'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/business/$slug'
    | '/cities/$city'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/regions/'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fuel'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/business/$slug'
    | '/cities/$city'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/regions'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fuel'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/business/$slug'
    | '/cities/$city'
    | '/messages/$conversationId'
    | '/provinces/$province'
    | '/regions/$region'
    | '/regions/'
    | '/barangays/$city/$barangay'
    | '/dashboard/business/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FuelRoute: typeof FuelRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  CitiesCityRoute: typeof CitiesCityRoute
  ProvincesProvinceRoute: typeof ProvincesProvinceRoute
  RegionsRegionRoute: typeof RegionsRegionRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
  BarangaysCityBarangayRoute: typeof BarangaysCityBarangayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$region': {
      id: '/regions/$region'
      path: '/regions/$region'
      fullPath: '/regions/$region'
      preLoaderRoute: typeof RegionsRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/$province': {
      id: '/provinces/$province'
      path: '/provinces/$province'
      fullPath: '/provinces/$province'
      preLoaderRoute: typeof ProvincesProvinceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/business/$id': {
      id: '/dashboard/business/$id'
      path: '/business/$id'
      fullPath: '/dashboard/business/$id'
      preLoaderRoute: typeof DashboardBusinessIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/barangays/$city/$barangay': {
      id: '/barangays/$city/$barangay'
      path: '/barangays/$city/$barangay'
      fullPath: '/barangays/$city/$barangay'
      preLoaderRoute: typeof BarangaysCityBarangayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBusinessIdRoute: typeof DashboardBusinessIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessIdRoute: DashboardBusinessIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FuelRoute: FuelRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  CitiesCityRoute: CitiesCityRoute,
  ProvincesProvinceRoute: ProvincesProvinceRoute,
  RegionsRegionRoute: RegionsRegionRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  BarangaysCityBarangayRoute: BarangaysCityBarangayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
